before_install: npm install npm@latest --global
cache:
  directories:
    - $HOME/.npm
dist: xenial
env:
  global:
    - secure: oKLVN4rr0h7rKQeLhJp9cT4I67f73EN2uI2i7YhZ8A6sM9z/o3GZWscoUkpBXDri2Yd5EM/a+VzFq3HrX0hja6Cl1VGzm4f+u+t0D3+bkI4qVoId8xsisw6xpkgaEAeDEgJkqXnyKgW9SCaw+a8UUz/CFmSe+Lifaio3cn66xO+YXW59O7K0kI4d/lHcnQ6sFWTAsFxuWLWeecL0lxFxRKEB4bJLu3YumVKrK0m6f06NLKpQJKJ/cm459pVdCzrJquOPlZTmAcm5H33mY1wZ89Fi3+x2zVQfp90Dw8caPPwGOhgz7bq1UQwQW6ENR0maV4LnDuoC5gKo7DoDUXgTSnkJcY7K9gblZl9kJp68QHkzqpFxc1lRZleV+K45WdZ+iAqjYwJ5P7NTmVgZkImk3ShgMWUnTKGwpOIxt1Le0Dk7VsUyjP9y8gPFK6lPZz3MsXhDZBl6Uniy7OC6+sTDvfAdwqIi25lgIexRJmhq58JaW1nTt8AkcUu2rtd1e3zFWjAoKhR8IeXYh6P0f4rlazDxHGmBk0fV15yKyIrX0RBbMc0a+bToCZy+EqsuTFeKtwALW7pcZ4sB6x3P4DlYXSAzRNlvwPitK9+UQo2z8niD0H28fhtk4b3EMRC+fEgKSZAScbDra/ifHB44Cj5szYCw22enJIdWUSKWrEIn40M=
    - secure: DU6Nzu5WBkpiiOo/v0HL7k/n+R3z1WLI/OtmO6wtxRMFuhD1ZKdwc/Ka4F759yzUvq/lRgReOUctrZKlVzQj/+4ulTy4ebotzeM3q1uWDuaB2jIPfvsviYDzxLflKvktE2RfojyTtAVuEO9Btr98dR6iroBsE3xUzdoOsHHboNmC3Zy7lcedaA9nGc36eA+lRRYMw0wJaJ5bGsOpmp01JYYdLiRko5MXTbaatwuXMOPcwTFgJ4CKgT1UBWq/SouYv87qJf32zKOMDMTjqwGJjETHCopKSEscUxCjw8HslCGBrzpnlAtU19gPfnAsqEbTbKJp2FAFe/+GXnS84jtFk7fXjBiXmPsXqTOGQ01EgsA9JOIdNzv/luiY/O23+YuuMZ8rocCXWhzBr2LWDoKU81sp4TeXFG6BIsNGe55JXMc42F+NfUGkgOtj69h8xWw/PhxAmVwN6qyH2fCHxv7Nyy2MG3MGd5DSgKxkzjJuRXTz1uiFUtxx1w7P4bw4CuAes17nCPxZ8FIJ884aEJsg9jNYxXAqnwt94rr7HLwExacfc+UW5f2EiKe/Uhae6NCYulmZ6+zl/zHhfIqiCcZcN2ulZO8mH2WKyf9CezDE1fyctcZA196z9YMl1YZuC8GZtAR/pygfCCtopm5/2jyEq0z2kxwJanKLa3mlTLLi2K4=
install: npm ci || (rm -rf node_modules && npm install)
language: node_js
node_js:
  - 10
  - 12
