before_install: npm install npm@latest --global
cache:
  directories:
    - $HOME/.npm
dist: xenial
env:
  global:
    - secure: pVMMmZ/zxGHJHjwiyutDfP98CyPLRqNfn3TWtChtRWiAbD5ShVNYXPbmjv28QAGDWg7QO0b9QDryzKfMPHi7ybTiLs1BGS5ZjXsKYw5kz6hPpPLgoo/CCpfm6oVh+yySd4lnlOQ3/ut8N8ihLXuj0T72GO3emLuzrZ1GizZnKijPo6yCLL8ueC45DFPCAGu9RX028apopnR8WNGdcquRQ8a7ZkJYgoVoi7Dfj/UDwz/5q5wmd0HzqbzuwuULvkC1sH0IL0erKC+7QH5Qt/0jT3UxGvZrg+M/v2c/RzZRc5xQSnvHWf6XcRcwoAmenjiXC9efusTCDAnklYkANza2fi9FsveuRn+B8Lgrr5oMbxAwR2W4BILIQrOa5RECDr6e/tD36OQ6JdR43xcomvtZtVWqhjkUIPL1JfWpYCxUygLupiPF6hXKYivNP0Uvw/003JzGRAx+Hk1KAlU7VhoBy0dt8k2Pw8ex/Of790NRgzxyQStvR8ofcOkY9ndnUFRN0+9UaPGUV+6ivEx0wR4/LRhx37n072i3wZaWyPc6XUkwOyvb5JQ8UKepe+ftSCR2Sv9IPtfbHaHXSnNXwVKAxO5sxGoSLt1S4eoTzlGBeEby8W8rctMty/Jxg9QiJPn/Zeiedy0Fcq5f6f6kEIi63pxSMf/lSbTvv2ro7xDiW7I=
    - secure: kttEwF2tvwWJAsflvCL1BWCz0wBwLuzkekeP+k2NPVxk8brHnJst+Qpk2ZOpAAsE8MQ9gK6DGcPHM6RzS3n8CzucnHt2fClStix8h6dz/2k7/Owa6Io7pWepRJcxSoeUQFK+2XGckoplKtzAaiJnQEjFUS6lG3RuEJt8Q2AZWKPNy5LJtd3EqqDwaCc+YUpw5Wi2IhYVgFfoMCY/Y0bC2UVjuWy+sOiN08trio4SDsAWe55+wulqAsSefn19cq2UVtXMVvWQlaukWzkLnIXSrRdxM8+WdNER35eS0fPu7ctumD2xtxi7gp4pVse2u8nBELAe5EhBMgRkjusukYzNqYRWulYYWKfm/jxdwk2zzmfjJZpH8WPKdTOrpvbrJ0ShN4nkWPf9fvD8SVLr3YWWnUGdtQBDyF9xKNa3kOvVJVJHlOvwMQDL4Rtxu7BNNZ6S0cy30dAhHqkB58N0s548rvNJSoqpLcD5zQ8YxZVH1UbFKY8X7n9/I5Ve/AH+hpIblj4lkXeZEyqH/q49PHVihepB4xFWD4HQvSvDCVF7alIObWD2Z7suTPWb1gbZOEXPtY9knvhoi6k0suZM74iNe+J+K7PgXUiquRvz7ymY5U4BarDd0ig0/Nz/tiAo36WZsr20BOt60Hgq1vsHaqhn8xj/KWvkuAyzqC5qUjDT7vU=
install: npm ci || (rm -rf node_modules && npm install)
language: node_js
node_js:
  - 10
  - 12
